# Generated by Django 3.0.7 on 2024-07-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
