# Generated by Django 4.2.14 on 2024-07-14 13:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_price_discount_alter_car_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='waeeanty',
            field=models.CharField(default='2 Years Limites', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Anti-theft Protection', 'Anti-theft Protection'), ('Automatic Climate Control', 'Automatic Climate Control'), ('Automatic Headlights', 'Automatic Headlights'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Wind Deflector', 'Wind Deflector'), ('Bluetooth Handset', 'Bluetooth Handset'), ('BOSE Surround Sound', 'BOSE Surround Sound'), ('Adaptive Cruise Control', 'Adaptive Cruise Control'), ('Burmester Surround Sound', 'Burmester Surround Sound'), ('Bi-Xenon Headlights', 'Bi-Xenon Headlights'), ('CD/DVD Autochanger', 'CD/DVD Autochanger')], max_length=372),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
