# Generated by Django 4.2.14 on 2024-07-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_waeeanty_alter_car_features_alter_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='Audi', max_length=100),
            preserve_default=False,
        ),
    ]
